---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0
  - name: debian-7.8
  - name: debian-8.0
suites:
  - name: default
    run_list:

      - recipe[jboss-dev-cookbook::default]

    attributes:
